### ISSUE TITLE
Incorrect Rendering

### ISSUE THREAD

**Issue by chaojian-zhang** [andersevenrud/osjs-terminal-application#1]
The output looks very different from the YouTube video (https://www.youtube.com/watch?v=CBEEoFixGts).

![Image 20201222 160852](https://user-images.githubusercontent.com/7077098/102933325-125c5900-4470-11eb-83a4-a09398a817f9.png)

**Comment by andersevenrud** [comment]
This should be fixed now. This is really just a prototype so it's using very outdated dependencies, of which some I have updated. But for the visual bug, I just worked around that.

Do the following:

1. Remove `node_modules`
2. Run `npm install`
3. Run `npm run build`

And it should work better.
